# Config file for automatic testing at travis-ci.org
language: python

python:
  - "3.6"

install:
  - pip install coveralls
  - pip install -r requirements-dev.txt

script:
  - find . -type f -name '*.pyc' -delete
  - pytest -s --cov=./helloworld --no-cov-on-fail --cov-config=.coveragerc ./helloworld

after_success:
  - coveralls
