# Config file for automatic testing at travis-ci.org
language: python

python:
  - "3.6"

install:
  - pip install coveralls
  - make install PYTHON_EXE=python

script:
  - make test

after_success:
  - coveralls
