# Config file for automatic testing at travis-ci.org
language: python

python:
  - "3.6"

install:
  - pip install coveralls
  - make setup_venv PYTHON_EXE=python

script:
  - find . -type f -name '*.pyc' -delete
  - make test

after_success:
  - coveralls
