apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: superduperminikuber
  labels:
    app: helloworld
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
  type: LoadBalancer
status:
  loadBalancer: {}
